# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |mouse xml /BOYFRIEND.xml/pico gay.xml
Friday night funkin psych engine
123/390/678 beta #run camera smooth
#custom controls lmao add#
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this 
(Main soft menu project add)
  Name app:friday night funkin psych engine
Name:forked from jigsaw 0.4.2
Info:com.shadowmario.psychengine
Add build
Android cl build android/open app test
Add character: BOYFRIEND.xml pico gay.xml
Custom characters:mouse.xml add to template 1
Custom controlls :hitbox custom pad downscroll middscrolls
Imput:none
Settings:anti instalasing low quality watermark
Bug found:1 watermark do not work:/   echo Add other actions to build,
          echo test, and deploy your project.
